"""Add core linguistic models: Sentence, Lexeme, WordForm with JSONB morphology and cascade deletes

Revision ID: 55266e67a6c7
Revises: 5968ef561dd7
Create Date: 2025-08-27 14:20:33.803994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55266e67a6c7'
down_revision: Union[str, Sequence[str], None] = '5968ef561dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
