"""Add core linguistic models: Sentence, Lexeme, WordForm with JSONB morphology and cascade deletes

Revision ID: f0672963fce5
Revises: 136c7b01855a
Create Date: 2025-08-26 15:27:56.179987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0672963fce5'
down_revision: Union[str, Sequence[str], None] = '136c7b01855a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=150), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'lemma', name='uix_language_lemma')
    )
    op.create_index(op.f('ix_lexemes_id'), 'lexemes', ['id'], unique=False)
    op.create_index(op.f('ix_lexemes_lemma'), 'lexemes', ['lemma'], unique=False)
    op.create_index(op.f('ix_lexemes_part_of_speech'), 'lexemes', ['part_of_speech'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_id', 'order_index', name='uix_text_sentence_order')
    )
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_order_index'), 'sentences', ['order_index'], unique=False)
    op.create_index(op.f('ix_sentences_text_id'), 'sentences', ['text_id'], unique=False)
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=True),
    sa.Column('surface_form', sa.String(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('morphology', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id', 'order_index', name='uix_sentence_word_order')
    )
    op.create_index(op.f('ix_word_forms_id'), 'word_forms', ['id'], unique=False)
    op.create_index(op.f('ix_word_forms_order_index'), 'word_forms', ['order_index'], unique=False)
    op.create_index(op.f('ix_word_forms_surface_form'), 'word_forms', ['surface_form'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_forms_surface_form'), table_name='word_forms')
    op.drop_index(op.f('ix_word_forms_order_index'), table_name='word_forms')
    op.drop_index(op.f('ix_word_forms_id'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index(op.f('ix_sentences_text_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_order_index'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_lexemes_part_of_speech'), table_name='lexemes')
    op.drop_index(op.f('ix_lexemes_lemma'), table_name='lexemes')
    op.drop_index(op.f('ix_lexemes_id'), table_name='lexemes')
    op.drop_table('lexemes')
    # ### end Alembic commands ###
